# Generated by Django 3.2.25 on 2026-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Project Lead', 'Project Lead')], default='User', max_length=20),
        ),
    ]
